# Environment Variables:
# - AWS_ACCESS_KEY_ID: Pulled from Bitbucket master
# - AWS_SECRET_ACCESS_KEY: Pulled from Bitbucket master
# - AWS_STAGE: Pulled from Deployments
image: node:16.13.0

definitions:
  services:
    docker:
      memory: 4096

  caches:
    node: node_modules      

  steps:
    - step: &step-install-dependencies
        name: Install Dependencies
        caches:
          - node        
        script:
          - npm ci
        artifacts:
          - node_modules/**
          - apps/**/node_modules/**
          - packages/**/node_modules/**
    - step: &step-build-packages
        name: Build Packages
        size: 2x
        script:
          - npm run build:packages
        artifacts:
          - packages/**/dist/**        
    - step: &step-branch-specific-steps
        size: 2x
        name: Build Apps
        script:
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" = "dev" ]; then
              npm run build:apps-changed:dev;
            fi
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" = "rc" ]; then
              npm run build:apps-changed:rc;
            fi
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" = "master" ]; then
              npm run build:apps-changed:master;
            fi
        artifacts:
          - packages/**/dist/**        


pipelines:
  pull-requests:
    '**':
      - step: *step-install-dependencies
      - step: *step-build-packages
      - step: *step-branch-specific-steps

